//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anakapur.SMSCAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SMSCountry WebService", ConfigurationName="SMSCAPI.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/getInbox", ReplyAction="*")]
        Anakapur.SMSCAPI.getInboxResponse getInbox(Anakapur.SMSCAPI.getInboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/getInbox", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.getInboxResponse> getInboxAsync(Anakapur.SMSCAPI.getInboxRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/MarkRead_inbox", ReplyAction="*")]
        Anakapur.SMSCAPI.MarkRead_inboxResponse MarkRead_inbox(Anakapur.SMSCAPI.MarkRead_inboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/MarkRead_inbox", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.MarkRead_inboxResponse> MarkRead_inboxAsync(Anakapur.SMSCAPI.MarkRead_inboxRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Mark_UnRead_inbox", ReplyAction="*")]
        Anakapur.SMSCAPI.Mark_UnRead_inboxResponse Mark_UnRead_inbox(Anakapur.SMSCAPI.Mark_UnRead_inboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Mark_UnRead_inbox", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.Mark_UnRead_inboxResponse> Mark_UnRead_inboxAsync(Anakapur.SMSCAPI.Mark_UnRead_inboxRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendTextSMS", ReplyAction="*")]
        Anakapur.SMSCAPI.SendTextSMSResponse SendTextSMS(Anakapur.SMSCAPI.SendTextSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendTextSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendTextSMSResponse> SendTextSMSAsync(Anakapur.SMSCAPI.SendTextSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendUnicodeSMS", ReplyAction="*")]
        Anakapur.SMSCAPI.SendUnicodeSMSResponse SendUnicodeSMS(Anakapur.SMSCAPI.SendUnicodeSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendUnicodeSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendUnicodeSMSResponse> SendUnicodeSMSAsync(Anakapur.SMSCAPI.SendUnicodeSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendPictureSMS", ReplyAction="*")]
        Anakapur.SMSCAPI.SendPictureSMSResponse SendPictureSMS(Anakapur.SMSCAPI.SendPictureSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendPictureSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendPictureSMSResponse> SendPictureSMSAsync(Anakapur.SMSCAPI.SendPictureSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendBinarySMS", ReplyAction="*")]
        Anakapur.SMSCAPI.SendBinarySMSResponse SendBinarySMS(Anakapur.SMSCAPI.SendBinarySMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendBinarySMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendBinarySMSResponse> SendBinarySMSAsync(Anakapur.SMSCAPI.SendBinarySMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendRingTone", ReplyAction="*")]
        Anakapur.SMSCAPI.SendRingToneResponse SendRingTone(Anakapur.SMSCAPI.SendRingToneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendRingTone", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendRingToneResponse> SendRingToneAsync(Anakapur.SMSCAPI.SendRingToneRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendLOGO", ReplyAction="*")]
        Anakapur.SMSCAPI.SendLOGOResponse SendLOGO(Anakapur.SMSCAPI.SendLOGORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendLOGO", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendLOGOResponse> SendLOGOAsync(Anakapur.SMSCAPI.SendLOGORequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendWapPush", ReplyAction="*")]
        Anakapur.SMSCAPI.SendWapPushResponse SendWapPush(Anakapur.SMSCAPI.SendWapPushRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendWapPush", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendWapPushResponse> SendWapPushAsync(Anakapur.SMSCAPI.SendWapPushRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendFlashSMS", ReplyAction="*")]
        Anakapur.SMSCAPI.SendFlashSMSResponse SendFlashSMS(Anakapur.SMSCAPI.SendFlashSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/SendFlashSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendFlashSMSResponse> SendFlashSMSAsync(Anakapur.SMSCAPI.SendFlashSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Getbalance", ReplyAction="*")]
        Anakapur.SMSCAPI.GetbalanceResponse Getbalance(Anakapur.SMSCAPI.GetbalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/Getbalance", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.GetbalanceResponse> GetbalanceAsync(Anakapur.SMSCAPI.GetbalanceRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/GetDeliveryReport", ReplyAction="*")]
        Anakapur.SMSCAPI.GetDeliveryReportResponse GetDeliveryReport(Anakapur.SMSCAPI.GetDeliveryReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/GetDeliveryReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.GetDeliveryReportResponse> GetDeliveryReportAsync(Anakapur.SMSCAPI.GetDeliveryReportRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace SMSCountry WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/sendMultiSMS", ReplyAction="*")]
        Anakapur.SMSCAPI.sendMultiSMSResponse sendMultiSMS(Anakapur.SMSCAPI.sendMultiSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SMSCountry WebService/sendMultiSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.sendMultiSMSResponse> sendMultiSMSAsync(Anakapur.SMSCAPI.sendMultiSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInbox", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.getInboxRequestBody Body;
        
        public getInboxRequest() {
        }
        
        public getInboxRequest(Anakapur.SMSCAPI.getInboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class getInboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ToDate;
        
        public getInboxRequestBody() {
        }
        
        public getInboxRequestBody(string username, string password, string FromDate, string ToDate) {
            this.username = username;
            this.password = password;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.getInboxResponseBody Body;
        
        public getInboxResponse() {
        }
        
        public getInboxResponse(Anakapur.SMSCAPI.getInboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class getInboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInboxResult;
        
        public getInboxResponseBody() {
        }
        
        public getInboxResponseBody(string getInboxResult) {
            this.getInboxResult = getInboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarkRead_inboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarkRead_inbox", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.MarkRead_inboxRequestBody Body;
        
        public MarkRead_inboxRequest() {
        }
        
        public MarkRead_inboxRequest(Anakapur.SMSCAPI.MarkRead_inboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class MarkRead_inboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int msgid;
        
        public MarkRead_inboxRequestBody() {
        }
        
        public MarkRead_inboxRequestBody(string username, string password, int msgid) {
            this.username = username;
            this.password = password;
            this.msgid = msgid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MarkRead_inboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MarkRead_inboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.MarkRead_inboxResponseBody Body;
        
        public MarkRead_inboxResponse() {
        }
        
        public MarkRead_inboxResponse(Anakapur.SMSCAPI.MarkRead_inboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class MarkRead_inboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MarkRead_inboxResult;
        
        public MarkRead_inboxResponseBody() {
        }
        
        public MarkRead_inboxResponseBody(string MarkRead_inboxResult) {
            this.MarkRead_inboxResult = MarkRead_inboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mark_UnRead_inboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mark_UnRead_inbox", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.Mark_UnRead_inboxRequestBody Body;
        
        public Mark_UnRead_inboxRequest() {
        }
        
        public Mark_UnRead_inboxRequest(Anakapur.SMSCAPI.Mark_UnRead_inboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class Mark_UnRead_inboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int msgid;
        
        public Mark_UnRead_inboxRequestBody() {
        }
        
        public Mark_UnRead_inboxRequestBody(string username, string password, int msgid) {
            this.username = username;
            this.password = password;
            this.msgid = msgid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Mark_UnRead_inboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mark_UnRead_inboxResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.Mark_UnRead_inboxResponseBody Body;
        
        public Mark_UnRead_inboxResponse() {
        }
        
        public Mark_UnRead_inboxResponse(Anakapur.SMSCAPI.Mark_UnRead_inboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class Mark_UnRead_inboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Mark_UnRead_inboxResult;
        
        public Mark_UnRead_inboxResponseBody() {
        }
        
        public Mark_UnRead_inboxResponseBody(string Mark_UnRead_inboxResult) {
            this.Mark_UnRead_inboxResult = Mark_UnRead_inboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextSMS", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendTextSMSRequestBody Body;
        
        public SendTextSMSRequest() {
        }
        
        public SendTextSMSRequest(Anakapur.SMSCAPI.SendTextSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendTextSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senderID;
        
        public SendTextSMSRequestBody() {
        }
        
        public SendTextSMSRequestBody(string username, string password, string mobilenumbers, string message, string senderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.senderID = senderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTextSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTextSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendTextSMSResponseBody Body;
        
        public SendTextSMSResponse() {
        }
        
        public SendTextSMSResponse(Anakapur.SMSCAPI.SendTextSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendTextSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendTextSMSResult;
        
        public SendTextSMSResponseBody() {
        }
        
        public SendTextSMSResponseBody(string SendTextSMSResult) {
            this.SendTextSMSResult = SendTextSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUnicodeSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUnicodeSMS", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendUnicodeSMSRequestBody Body;
        
        public SendUnicodeSMSRequest() {
        }
        
        public SendUnicodeSMSRequest(Anakapur.SMSCAPI.SendUnicodeSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendUnicodeSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senderID;
        
        public SendUnicodeSMSRequestBody() {
        }
        
        public SendUnicodeSMSRequestBody(string username, string password, string mobilenumbers, string message, string senderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.senderID = senderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUnicodeSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUnicodeSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendUnicodeSMSResponseBody Body;
        
        public SendUnicodeSMSResponse() {
        }
        
        public SendUnicodeSMSResponse(Anakapur.SMSCAPI.SendUnicodeSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendUnicodeSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendUnicodeSMSResult;
        
        public SendUnicodeSMSResponseBody() {
        }
        
        public SendUnicodeSMSResponseBody(string SendUnicodeSMSResult) {
            this.SendUnicodeSMSResult = SendUnicodeSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPictureSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPictureSMS", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendPictureSMSRequestBody Body;
        
        public SendPictureSMSRequest() {
        }
        
        public SendPictureSMSRequest(Anakapur.SMSCAPI.SendPictureSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendPictureSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendPictureSMSRequestBody() {
        }
        
        public SendPictureSMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPictureSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPictureSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendPictureSMSResponseBody Body;
        
        public SendPictureSMSResponse() {
        }
        
        public SendPictureSMSResponse(Anakapur.SMSCAPI.SendPictureSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendPictureSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendPictureSMSResult;
        
        public SendPictureSMSResponseBody() {
        }
        
        public SendPictureSMSResponseBody(string SendPictureSMSResult) {
            this.SendPictureSMSResult = SendPictureSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBinarySMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBinarySMS", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendBinarySMSRequestBody Body;
        
        public SendBinarySMSRequest() {
        }
        
        public SendBinarySMSRequest(Anakapur.SMSCAPI.SendBinarySMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendBinarySMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendBinarySMSRequestBody() {
        }
        
        public SendBinarySMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBinarySMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendBinarySMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendBinarySMSResponseBody Body;
        
        public SendBinarySMSResponse() {
        }
        
        public SendBinarySMSResponse(Anakapur.SMSCAPI.SendBinarySMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendBinarySMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendBinarySMSResult;
        
        public SendBinarySMSResponseBody() {
        }
        
        public SendBinarySMSResponseBody(string SendBinarySMSResult) {
            this.SendBinarySMSResult = SendBinarySMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRingToneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRingTone", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendRingToneRequestBody Body;
        
        public SendRingToneRequest() {
        }
        
        public SendRingToneRequest(Anakapur.SMSCAPI.SendRingToneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendRingToneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendRingToneRequestBody() {
        }
        
        public SendRingToneRequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRingToneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendRingToneResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendRingToneResponseBody Body;
        
        public SendRingToneResponse() {
        }
        
        public SendRingToneResponse(Anakapur.SMSCAPI.SendRingToneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendRingToneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendRingToneResult;
        
        public SendRingToneResponseBody() {
        }
        
        public SendRingToneResponseBody(string SendRingToneResult) {
            this.SendRingToneResult = SendRingToneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendLOGORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendLOGO", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendLOGORequestBody Body;
        
        public SendLOGORequest() {
        }
        
        public SendLOGORequest(Anakapur.SMSCAPI.SendLOGORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendLOGORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendLOGORequestBody() {
        }
        
        public SendLOGORequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendLOGOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendLOGOResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendLOGOResponseBody Body;
        
        public SendLOGOResponse() {
        }
        
        public SendLOGOResponse(Anakapur.SMSCAPI.SendLOGOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendLOGOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendLOGOResult;
        
        public SendLOGOResponseBody() {
        }
        
        public SendLOGOResponseBody(string SendLOGOResult) {
            this.SendLOGOResult = SendLOGOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWapPushRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWapPush", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendWapPushRequestBody Body;
        
        public SendWapPushRequest() {
        }
        
        public SendWapPushRequest(Anakapur.SMSCAPI.SendWapPushRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendWapPushRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WapUrl;
        
        public SendWapPushRequestBody() {
        }
        
        public SendWapPushRequestBody(string username, string password, string mobilenumbers, string message, string SenderID, string WapUrl) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
            this.WapUrl = WapUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWapPushResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWapPushResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendWapPushResponseBody Body;
        
        public SendWapPushResponse() {
        }
        
        public SendWapPushResponse(Anakapur.SMSCAPI.SendWapPushResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendWapPushResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWapPushResult;
        
        public SendWapPushResponseBody() {
        }
        
        public SendWapPushResponseBody(string SendWapPushResult) {
            this.SendWapPushResult = SendWapPushResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFlashSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFlashSMS", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendFlashSMSRequestBody Body;
        
        public SendFlashSMSRequest() {
        }
        
        public SendFlashSMSRequest(Anakapur.SMSCAPI.SendFlashSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendFlashSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobilenumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SenderID;
        
        public SendFlashSMSRequestBody() {
        }
        
        public SendFlashSMSRequestBody(string username, string password, string mobilenumbers, string message, string SenderID) {
            this.username = username;
            this.password = password;
            this.mobilenumbers = mobilenumbers;
            this.message = message;
            this.SenderID = SenderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFlashSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendFlashSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.SendFlashSMSResponseBody Body;
        
        public SendFlashSMSResponse() {
        }
        
        public SendFlashSMSResponse(Anakapur.SMSCAPI.SendFlashSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class SendFlashSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendFlashSMSResult;
        
        public SendFlashSMSResponseBody() {
        }
        
        public SendFlashSMSResponseBody(string SendFlashSMSResult) {
            this.SendFlashSMSResult = SendFlashSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getbalance", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.GetbalanceRequestBody Body;
        
        public GetbalanceRequest() {
        }
        
        public GetbalanceRequest(Anakapur.SMSCAPI.GetbalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetbalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetbalanceRequestBody() {
        }
        
        public GetbalanceRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetbalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetbalanceResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.GetbalanceResponseBody Body;
        
        public GetbalanceResponse() {
        }
        
        public GetbalanceResponse(Anakapur.SMSCAPI.GetbalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetbalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetbalanceResult;
        
        public GetbalanceResponseBody() {
        }
        
        public GetbalanceResponseBody(string GetbalanceResult) {
            this.GetbalanceResult = GetbalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryReport", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.GetDeliveryReportRequestBody Body;
        
        public GetDeliveryReportRequest() {
        }
        
        public GetDeliveryReportRequest(Anakapur.SMSCAPI.GetDeliveryReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetDeliveryReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong SMS_Job_No;
        
        public GetDeliveryReportRequestBody() {
        }
        
        public GetDeliveryReportRequestBody(string username, string password, ulong SMS_Job_No) {
            this.username = username;
            this.password = password;
            this.SMS_Job_No = SMS_Job_No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryReportResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.GetDeliveryReportResponseBody Body;
        
        public GetDeliveryReportResponse() {
        }
        
        public GetDeliveryReportResponse(Anakapur.SMSCAPI.GetDeliveryReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class GetDeliveryReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeliveryReportResult;
        
        public GetDeliveryReportResponseBody() {
        }
        
        public GetDeliveryReportResponseBody(string GetDeliveryReportResult) {
            this.GetDeliveryReportResult = GetDeliveryReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMultiSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMultiSMS", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.sendMultiSMSRequestBody Body;
        
        public sendMultiSMSRequest() {
        }
        
        public sendMultiSMSRequest(Anakapur.SMSCAPI.sendMultiSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class sendMultiSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MNO_MSG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public char dr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string wapurl;
        
        public sendMultiSMSRequestBody() {
        }
        
        public sendMultiSMSRequestBody(string user, string password, string MNO_MSG, string sid, string mtype, char dr, string wapurl) {
            this.user = user;
            this.password = password;
            this.MNO_MSG = MNO_MSG;
            this.sid = sid;
            this.mtype = mtype;
            this.dr = dr;
            this.wapurl = wapurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMultiSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMultiSMSResponse", Namespace="SMSCountry WebService", Order=0)]
        public Anakapur.SMSCAPI.sendMultiSMSResponseBody Body;
        
        public sendMultiSMSResponse() {
        }
        
        public sendMultiSMSResponse(Anakapur.SMSCAPI.sendMultiSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SMSCountry WebService")]
    public partial class sendMultiSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendMultiSMSResult;
        
        public sendMultiSMSResponseBody() {
        }
        
        public sendMultiSMSResponseBody(string sendMultiSMSResult) {
            this.sendMultiSMSResult = sendMultiSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Anakapur.SMSCAPI.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Anakapur.SMSCAPI.ServiceSoap>, Anakapur.SMSCAPI.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.getInboxResponse Anakapur.SMSCAPI.ServiceSoap.getInbox(Anakapur.SMSCAPI.getInboxRequest request) {
            return base.Channel.getInbox(request);
        }
        
        public string getInbox(string username, string password, string FromDate, string ToDate) {
            Anakapur.SMSCAPI.getInboxRequest inValue = new Anakapur.SMSCAPI.getInboxRequest();
            inValue.Body = new Anakapur.SMSCAPI.getInboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            Anakapur.SMSCAPI.getInboxResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).getInbox(inValue);
            return retVal.Body.getInboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.getInboxResponse> Anakapur.SMSCAPI.ServiceSoap.getInboxAsync(Anakapur.SMSCAPI.getInboxRequest request) {
            return base.Channel.getInboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.getInboxResponse> getInboxAsync(string username, string password, string FromDate, string ToDate) {
            Anakapur.SMSCAPI.getInboxRequest inValue = new Anakapur.SMSCAPI.getInboxRequest();
            inValue.Body = new Anakapur.SMSCAPI.getInboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.FromDate = FromDate;
            inValue.Body.ToDate = ToDate;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).getInboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.MarkRead_inboxResponse Anakapur.SMSCAPI.ServiceSoap.MarkRead_inbox(Anakapur.SMSCAPI.MarkRead_inboxRequest request) {
            return base.Channel.MarkRead_inbox(request);
        }
        
        public string MarkRead_inbox(string username, string password, int msgid) {
            Anakapur.SMSCAPI.MarkRead_inboxRequest inValue = new Anakapur.SMSCAPI.MarkRead_inboxRequest();
            inValue.Body = new Anakapur.SMSCAPI.MarkRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            Anakapur.SMSCAPI.MarkRead_inboxResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).MarkRead_inbox(inValue);
            return retVal.Body.MarkRead_inboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.MarkRead_inboxResponse> Anakapur.SMSCAPI.ServiceSoap.MarkRead_inboxAsync(Anakapur.SMSCAPI.MarkRead_inboxRequest request) {
            return base.Channel.MarkRead_inboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.MarkRead_inboxResponse> MarkRead_inboxAsync(string username, string password, int msgid) {
            Anakapur.SMSCAPI.MarkRead_inboxRequest inValue = new Anakapur.SMSCAPI.MarkRead_inboxRequest();
            inValue.Body = new Anakapur.SMSCAPI.MarkRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).MarkRead_inboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.Mark_UnRead_inboxResponse Anakapur.SMSCAPI.ServiceSoap.Mark_UnRead_inbox(Anakapur.SMSCAPI.Mark_UnRead_inboxRequest request) {
            return base.Channel.Mark_UnRead_inbox(request);
        }
        
        public string Mark_UnRead_inbox(string username, string password, int msgid) {
            Anakapur.SMSCAPI.Mark_UnRead_inboxRequest inValue = new Anakapur.SMSCAPI.Mark_UnRead_inboxRequest();
            inValue.Body = new Anakapur.SMSCAPI.Mark_UnRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            Anakapur.SMSCAPI.Mark_UnRead_inboxResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).Mark_UnRead_inbox(inValue);
            return retVal.Body.Mark_UnRead_inboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.Mark_UnRead_inboxResponse> Anakapur.SMSCAPI.ServiceSoap.Mark_UnRead_inboxAsync(Anakapur.SMSCAPI.Mark_UnRead_inboxRequest request) {
            return base.Channel.Mark_UnRead_inboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.Mark_UnRead_inboxResponse> Mark_UnRead_inboxAsync(string username, string password, int msgid) {
            Anakapur.SMSCAPI.Mark_UnRead_inboxRequest inValue = new Anakapur.SMSCAPI.Mark_UnRead_inboxRequest();
            inValue.Body = new Anakapur.SMSCAPI.Mark_UnRead_inboxRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.msgid = msgid;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).Mark_UnRead_inboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.SendTextSMSResponse Anakapur.SMSCAPI.ServiceSoap.SendTextSMS(Anakapur.SMSCAPI.SendTextSMSRequest request) {
            return base.Channel.SendTextSMS(request);
        }
        
        public string SendTextSMS(string username, string password, string mobilenumbers, string message, string senderID) {
            Anakapur.SMSCAPI.SendTextSMSRequest inValue = new Anakapur.SMSCAPI.SendTextSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendTextSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            Anakapur.SMSCAPI.SendTextSMSResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendTextSMS(inValue);
            return retVal.Body.SendTextSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendTextSMSResponse> Anakapur.SMSCAPI.ServiceSoap.SendTextSMSAsync(Anakapur.SMSCAPI.SendTextSMSRequest request) {
            return base.Channel.SendTextSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendTextSMSResponse> SendTextSMSAsync(string username, string password, string mobilenumbers, string message, string senderID) {
            Anakapur.SMSCAPI.SendTextSMSRequest inValue = new Anakapur.SMSCAPI.SendTextSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendTextSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendTextSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.SendUnicodeSMSResponse Anakapur.SMSCAPI.ServiceSoap.SendUnicodeSMS(Anakapur.SMSCAPI.SendUnicodeSMSRequest request) {
            return base.Channel.SendUnicodeSMS(request);
        }
        
        public string SendUnicodeSMS(string username, string password, string mobilenumbers, string message, string senderID) {
            Anakapur.SMSCAPI.SendUnicodeSMSRequest inValue = new Anakapur.SMSCAPI.SendUnicodeSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendUnicodeSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            Anakapur.SMSCAPI.SendUnicodeSMSResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendUnicodeSMS(inValue);
            return retVal.Body.SendUnicodeSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendUnicodeSMSResponse> Anakapur.SMSCAPI.ServiceSoap.SendUnicodeSMSAsync(Anakapur.SMSCAPI.SendUnicodeSMSRequest request) {
            return base.Channel.SendUnicodeSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendUnicodeSMSResponse> SendUnicodeSMSAsync(string username, string password, string mobilenumbers, string message, string senderID) {
            Anakapur.SMSCAPI.SendUnicodeSMSRequest inValue = new Anakapur.SMSCAPI.SendUnicodeSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendUnicodeSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.senderID = senderID;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendUnicodeSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.SendPictureSMSResponse Anakapur.SMSCAPI.ServiceSoap.SendPictureSMS(Anakapur.SMSCAPI.SendPictureSMSRequest request) {
            return base.Channel.SendPictureSMS(request);
        }
        
        public string SendPictureSMS(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendPictureSMSRequest inValue = new Anakapur.SMSCAPI.SendPictureSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendPictureSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            Anakapur.SMSCAPI.SendPictureSMSResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendPictureSMS(inValue);
            return retVal.Body.SendPictureSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendPictureSMSResponse> Anakapur.SMSCAPI.ServiceSoap.SendPictureSMSAsync(Anakapur.SMSCAPI.SendPictureSMSRequest request) {
            return base.Channel.SendPictureSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendPictureSMSResponse> SendPictureSMSAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendPictureSMSRequest inValue = new Anakapur.SMSCAPI.SendPictureSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendPictureSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendPictureSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.SendBinarySMSResponse Anakapur.SMSCAPI.ServiceSoap.SendBinarySMS(Anakapur.SMSCAPI.SendBinarySMSRequest request) {
            return base.Channel.SendBinarySMS(request);
        }
        
        public string SendBinarySMS(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendBinarySMSRequest inValue = new Anakapur.SMSCAPI.SendBinarySMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendBinarySMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            Anakapur.SMSCAPI.SendBinarySMSResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendBinarySMS(inValue);
            return retVal.Body.SendBinarySMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendBinarySMSResponse> Anakapur.SMSCAPI.ServiceSoap.SendBinarySMSAsync(Anakapur.SMSCAPI.SendBinarySMSRequest request) {
            return base.Channel.SendBinarySMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendBinarySMSResponse> SendBinarySMSAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendBinarySMSRequest inValue = new Anakapur.SMSCAPI.SendBinarySMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendBinarySMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendBinarySMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.SendRingToneResponse Anakapur.SMSCAPI.ServiceSoap.SendRingTone(Anakapur.SMSCAPI.SendRingToneRequest request) {
            return base.Channel.SendRingTone(request);
        }
        
        public string SendRingTone(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendRingToneRequest inValue = new Anakapur.SMSCAPI.SendRingToneRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendRingToneRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            Anakapur.SMSCAPI.SendRingToneResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendRingTone(inValue);
            return retVal.Body.SendRingToneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendRingToneResponse> Anakapur.SMSCAPI.ServiceSoap.SendRingToneAsync(Anakapur.SMSCAPI.SendRingToneRequest request) {
            return base.Channel.SendRingToneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendRingToneResponse> SendRingToneAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendRingToneRequest inValue = new Anakapur.SMSCAPI.SendRingToneRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendRingToneRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendRingToneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.SendLOGOResponse Anakapur.SMSCAPI.ServiceSoap.SendLOGO(Anakapur.SMSCAPI.SendLOGORequest request) {
            return base.Channel.SendLOGO(request);
        }
        
        public string SendLOGO(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendLOGORequest inValue = new Anakapur.SMSCAPI.SendLOGORequest();
            inValue.Body = new Anakapur.SMSCAPI.SendLOGORequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            Anakapur.SMSCAPI.SendLOGOResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendLOGO(inValue);
            return retVal.Body.SendLOGOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendLOGOResponse> Anakapur.SMSCAPI.ServiceSoap.SendLOGOAsync(Anakapur.SMSCAPI.SendLOGORequest request) {
            return base.Channel.SendLOGOAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendLOGOResponse> SendLOGOAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendLOGORequest inValue = new Anakapur.SMSCAPI.SendLOGORequest();
            inValue.Body = new Anakapur.SMSCAPI.SendLOGORequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendLOGOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.SendWapPushResponse Anakapur.SMSCAPI.ServiceSoap.SendWapPush(Anakapur.SMSCAPI.SendWapPushRequest request) {
            return base.Channel.SendWapPush(request);
        }
        
        public string SendWapPush(string username, string password, string mobilenumbers, string message, string SenderID, string WapUrl) {
            Anakapur.SMSCAPI.SendWapPushRequest inValue = new Anakapur.SMSCAPI.SendWapPushRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendWapPushRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            inValue.Body.WapUrl = WapUrl;
            Anakapur.SMSCAPI.SendWapPushResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendWapPush(inValue);
            return retVal.Body.SendWapPushResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendWapPushResponse> Anakapur.SMSCAPI.ServiceSoap.SendWapPushAsync(Anakapur.SMSCAPI.SendWapPushRequest request) {
            return base.Channel.SendWapPushAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendWapPushResponse> SendWapPushAsync(string username, string password, string mobilenumbers, string message, string SenderID, string WapUrl) {
            Anakapur.SMSCAPI.SendWapPushRequest inValue = new Anakapur.SMSCAPI.SendWapPushRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendWapPushRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            inValue.Body.WapUrl = WapUrl;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendWapPushAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.SendFlashSMSResponse Anakapur.SMSCAPI.ServiceSoap.SendFlashSMS(Anakapur.SMSCAPI.SendFlashSMSRequest request) {
            return base.Channel.SendFlashSMS(request);
        }
        
        public string SendFlashSMS(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendFlashSMSRequest inValue = new Anakapur.SMSCAPI.SendFlashSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendFlashSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            Anakapur.SMSCAPI.SendFlashSMSResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendFlashSMS(inValue);
            return retVal.Body.SendFlashSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendFlashSMSResponse> Anakapur.SMSCAPI.ServiceSoap.SendFlashSMSAsync(Anakapur.SMSCAPI.SendFlashSMSRequest request) {
            return base.Channel.SendFlashSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.SendFlashSMSResponse> SendFlashSMSAsync(string username, string password, string mobilenumbers, string message, string SenderID) {
            Anakapur.SMSCAPI.SendFlashSMSRequest inValue = new Anakapur.SMSCAPI.SendFlashSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.SendFlashSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.mobilenumbers = mobilenumbers;
            inValue.Body.message = message;
            inValue.Body.SenderID = SenderID;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).SendFlashSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.GetbalanceResponse Anakapur.SMSCAPI.ServiceSoap.Getbalance(Anakapur.SMSCAPI.GetbalanceRequest request) {
            return base.Channel.Getbalance(request);
        }
        
        public string Getbalance(string username, string password) {
            Anakapur.SMSCAPI.GetbalanceRequest inValue = new Anakapur.SMSCAPI.GetbalanceRequest();
            inValue.Body = new Anakapur.SMSCAPI.GetbalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Anakapur.SMSCAPI.GetbalanceResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).Getbalance(inValue);
            return retVal.Body.GetbalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.GetbalanceResponse> Anakapur.SMSCAPI.ServiceSoap.GetbalanceAsync(Anakapur.SMSCAPI.GetbalanceRequest request) {
            return base.Channel.GetbalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.GetbalanceResponse> GetbalanceAsync(string username, string password) {
            Anakapur.SMSCAPI.GetbalanceRequest inValue = new Anakapur.SMSCAPI.GetbalanceRequest();
            inValue.Body = new Anakapur.SMSCAPI.GetbalanceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).GetbalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.GetDeliveryReportResponse Anakapur.SMSCAPI.ServiceSoap.GetDeliveryReport(Anakapur.SMSCAPI.GetDeliveryReportRequest request) {
            return base.Channel.GetDeliveryReport(request);
        }
        
        public string GetDeliveryReport(string username, string password, ulong SMS_Job_No) {
            Anakapur.SMSCAPI.GetDeliveryReportRequest inValue = new Anakapur.SMSCAPI.GetDeliveryReportRequest();
            inValue.Body = new Anakapur.SMSCAPI.GetDeliveryReportRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.SMS_Job_No = SMS_Job_No;
            Anakapur.SMSCAPI.GetDeliveryReportResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).GetDeliveryReport(inValue);
            return retVal.Body.GetDeliveryReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.GetDeliveryReportResponse> Anakapur.SMSCAPI.ServiceSoap.GetDeliveryReportAsync(Anakapur.SMSCAPI.GetDeliveryReportRequest request) {
            return base.Channel.GetDeliveryReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.GetDeliveryReportResponse> GetDeliveryReportAsync(string username, string password, ulong SMS_Job_No) {
            Anakapur.SMSCAPI.GetDeliveryReportRequest inValue = new Anakapur.SMSCAPI.GetDeliveryReportRequest();
            inValue.Body = new Anakapur.SMSCAPI.GetDeliveryReportRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.SMS_Job_No = SMS_Job_No;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).GetDeliveryReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Anakapur.SMSCAPI.sendMultiSMSResponse Anakapur.SMSCAPI.ServiceSoap.sendMultiSMS(Anakapur.SMSCAPI.sendMultiSMSRequest request) {
            return base.Channel.sendMultiSMS(request);
        }
        
        public string sendMultiSMS(string user, string password, string MNO_MSG, string sid, string mtype, char dr, string wapurl) {
            Anakapur.SMSCAPI.sendMultiSMSRequest inValue = new Anakapur.SMSCAPI.sendMultiSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.sendMultiSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.MNO_MSG = MNO_MSG;
            inValue.Body.sid = sid;
            inValue.Body.mtype = mtype;
            inValue.Body.dr = dr;
            inValue.Body.wapurl = wapurl;
            Anakapur.SMSCAPI.sendMultiSMSResponse retVal = ((Anakapur.SMSCAPI.ServiceSoap)(this)).sendMultiSMS(inValue);
            return retVal.Body.sendMultiSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Anakapur.SMSCAPI.sendMultiSMSResponse> Anakapur.SMSCAPI.ServiceSoap.sendMultiSMSAsync(Anakapur.SMSCAPI.sendMultiSMSRequest request) {
            return base.Channel.sendMultiSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Anakapur.SMSCAPI.sendMultiSMSResponse> sendMultiSMSAsync(string user, string password, string MNO_MSG, string sid, string mtype, char dr, string wapurl) {
            Anakapur.SMSCAPI.sendMultiSMSRequest inValue = new Anakapur.SMSCAPI.sendMultiSMSRequest();
            inValue.Body = new Anakapur.SMSCAPI.sendMultiSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.MNO_MSG = MNO_MSG;
            inValue.Body.sid = sid;
            inValue.Body.mtype = mtype;
            inValue.Body.dr = dr;
            inValue.Body.wapurl = wapurl;
            return ((Anakapur.SMSCAPI.ServiceSoap)(this)).sendMultiSMSAsync(inValue);
        }
    }
}
